### ISSUE TITLE
Release automation broken on this repository?

### ISSUE THREAD

**Issue by Ocramius** [laminas/laminas-cache-storage-adapter-benchmark#11]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.2.0

#### Summary

See https://github.com/laminas/laminas-cache-storage-adapter-benchmark/actions/runs/3655683449/jobs/6177279507

Apparently, our release automation is failing to create a release:

```
In invariant_violation.php line 16:
                                                
  [Psl\Exception\InvariantViolationException]   
  Failed to create release through GitHub API.  
```

Branch switching also didn't work.

**Comment by boesing** [comment]
Yes, the automatic-releases is broken in plenty of those components which were created after the initial introduction of the automatic-releases.

I have no idea if I do not have sufficient permissions or sth. like this but it seems that the secrets needed to access the API is not available for some components.

Sadly the error reporting of automatic-releases is not really clear about the "why". Asserting stuff is good for the happy-path but in case a problem occurs, it gives exactly no information about the problem itself.

Thats why I was not able to fix that problem but I could narrow it down to the place where the github release is actually created. Maybe the github release does not allow empty release description or sth. like this, but I have no idea without proper error reporting.

**Comment by Ocramius** [comment]
> I have no idea if I do not have sufficient permissions or sth.

Hmm, the organization secrets are not overridden here: same permissions as everything else.

> Asserting stuff is good for the happy-path but in case a problem occurs, it gives exactly no information about the problem itself.

We could raise logging verbosity (needs ejecting of the reusable workflow, while we try it). 

I had similar issues in https://github.com/Roave/DocbookTool/issues/232

Practically, we set the `LOG_LEVEL` environment variable to `DEBUG`, and we should see full request/response cycles.

Ref: https://github.com/laminas/automatic-releases/blob/f01e2555db36adfa0ba743b299dcd60d32394e80/src/Environment/EnvironmentVariables.php#L70
Ref: https://github.com/laminas/automatic-releases/issues/205

**Comment by Xerkus** [comment]
Whatever it was, it was resolved.
